# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------


# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

# Add project root to Python path
sys.path.insert(0, os.path.abspath('..'))

# -- Project information -----------------------------------------------------


project = 'Thymeleaf FileInput with MinIO'
copyright = '2025, Zademy'
author = 'Zademy'

# Versiones para mostrar en la documentación
version = '1.0'  # Versión corta, por ejemplo '1.0'
release = '1.0.0'  # Versión completa, por ejemplo '1.0.0'

# Información para enlaces a GitHub y versiones
html_context = {
    'display_github': True,
    'github_user': 'zademy',
    'github_repo': 'thymeleaf-fileinput-minio',
    'github_version': 'master',  # Rama o tag que se está visualizando
    'conf_py_path': '/docs/',    # Ruta al directorio docs en tu repositorio
}

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.githubpages',
]

# Configuración del tema de Read the Docs
import sphinx_rtd_theme
html_theme = 'sphinx_rtd_theme'
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# No usar plantillas ni estilos personalizados
html_additional_pages = {}
html_css_files = []

# Configuración del tema RTD con todas las opciones disponibles
html_theme_options = {
    # Opciones de análisis
    'analytics_id': '',  # Proporcionado por Google en tu dashboard (dejar vacío si no se usa)
    'analytics_anonymize_ip': False,
    
    # Opciones de apariencia (valores por defecto)
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'vcs_pageview_mode': '',
    
    # Opciones de menú desplegable
    'flyout_display': 'hidden',  # Comportamiento del menú desplegable
    
    # Selectores
    'version_selector': True,  # Mostrar selector de versiones
    'language_selector': True,  # Mostrar selector de idiomas
    
    # Opciones de tabla de contenido (TOC)
    'collapse_navigation': True,  # Colapsar la navegación
    'sticky_navigation': True,  # Navegación fija al desplazarse
    'navigation_depth': 4,  # Profundidad de la navegación
    'includehidden': True,  # Incluir elementos ocultos en la navegación
    'titles_only': False  # Mostrar solo títulos en la navegación
}

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'es'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', 'venv', '.venv', 'build', 'dist']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.
# El tema ya se configuró anteriormente en el archivo
# No es necesario volver a definirlo aquí

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']
#
# html_sidebars = {}

# -- Options for HTMLHelp output ------------------------------------------


# Output file base name for HTML help builder.
htmlhelp_basename = 'ThymeleafFileInputMiniodoc'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']
#
# html_sidebars = {}

# -- Extension configuration -------------------------------------------------

# Napoleon settings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = True
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_type_aliases = None

# Autodoc settings
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'exclude-members': '__weakref__'
}

# Mock dependencies that might not be available during documentation build
autodoc_mock_imports = [
    'org.springframework',
    'lombok',
    'jakarta',
    'io.minio',
    'java',
    'javax',
]

# Configuración de sufijos de archivo
source_suffix = '.rst'

# -- Options for internationalization ----------------------------------------
# The language for content autogenerated by Sphinx
language = 'es'

# -- Options for ReadTheDocs -------------------------------------------------
# ReadTheDocs specific settings
html_theme_options = {
    'navigation_depth': 4,
    'collapse_navigation': False,
    'sticky_navigation': True,
    'includehidden': True,
    'titles_only': False
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = False

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = False

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = True

# No usar estilos personalizados
html_css_files = []
html_js_files = []
